### ISSUE TITLE
Can't retrieve from PACS only with Horos(Osirix , Radiant, etc working)

### ISSUE THREAD

**Issue by johnpap72** [horosproject/horos#404]
I install in a synology DS218 the PACS package and working ok but i am able to query with Horos client but no retrieve. The Dcm4chee -arc run over WildFly and Keycloak. I am getting the following error when i try to C-GET:

IdentifierDoesNotMatchSOPClass
#Dicom Data Set
#Used TransferSyntax: LittleEndianImplicit
(0000,0901) AT (0020,000e)   # 4,1
OffendingElement
(0000,0902) LO (Missing SeriesInstanceUID)
(0020,000E) # 38,1 ErrorComment

the server logs this:

2018-10-03 14:24:45,087 INFO  [org.dcm4chee.arc.store.scu.impl.RetrieveTaskImpl] (EE-ManagedExecutorService-default-Thread-4) DCM4CHEE<-Ioannis-MacBook-(162): failed to send Instance[iuid=1.2.840.113619.2.259.6945.3446810.21523.1437468192.498,cuid=1.2.840.10008.5.1.4.1.1.4] to Ioannis-MacBook-:: org.dcm4che3.net.NoRoleSelectionException: No Role Selection for SOP Class 1.2.840.10008.5.1.4.1.1.4 - MR Image Storage as SCU negotiated
	at org.dcm4che3.net.Association.checkIsSCU(Association.java:259)
	at org.dcm4che3.net.Association.cstore(Association.java:880)
	at org.dcm4che3.net.Association.cstore(Association.java:873)
	at org.dcm4chee.arc.store.scu.impl.RetrieveTaskImpl.store(RetrieveTaskImpl.java:165)
	at org.dcm4chee.arc.store.scu.impl.RetrieveTaskImpl.run(RetrieveTaskImpl.java:126)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)

When i try with other clients like Osirix or Radiant with the same setup i can query and retrieve with C-GET.

Thank you in advance for your help,
Ioannis Papadopoulos.

**Comment by juandelsolar** [comment]
I have the same issue.
Here is a simple video that explain this:
https://youtu.be/E-OZ1aXODW4

The first one is Horlix, the second one is Horos, and the last one is Osirix.

**Comment by Hiroaki-Inomata** [comment]
Hi,
HorliX MacApp version has been sandboxed. So it may be difficult to retrieve from other certain  DICOM node.
However, HorliX NSB -Non SandBoxing version- can retrieve from other PACS with C-GET like the following:
https://www.youtube.com/watch?v=kL7KmkofLfY&feature=youtu.be

HorliX NSB is distributed via our own site but here is Horos issues page. I have no intention to advertise our product.

As you have pointed out, HorliX/Horos couldn't  communicate well with Dcm4chee-arc.
I will check it.

**Comment by tecsal** [comment]
I ran into a simular issue writing a proxy for C_GET impl... until I saw error between Horos and Dcm4chee.

I just copy this fix into :
org.dcm4chee.arc.store.scu.impl.RetrieveTaskImpl : 179

```
//storeas.cstore(cuid, iuid, priority, data, tsuid, rspHandler);
PresentationContext pc = storeas.pcFor(cuid, tsuid);
Attributes cstorerq = Commands.mkCStoreRQ(rspHandler.getMessageID(), cuid, iuid, priority);
storeas.invoke(pc, cstorerq, data, rspHandler, 0);
```

Then I recompiled dcm4chee-arc-strore-scu-5.18.0.jar and re-zip it into dcm4chee-arc-ear-5.18.0-psql.ear and deploy it into wildfly, and then it runs well for Horos :-)

- show quoted text -
